### ISSUE TITLE
reverse-map of "reason"

### ISSUE THREAD

**Issue by otheus** [phemmer/ruby-corosync#2]
Perhapse this is really a ruby-noob question, but is there anyway given the code as-is to get the symbolic reason from the numeric mapping? That is, can I somehow access Corosync::cpg_reason_t, so that I can determine/inspect  the symbol ":nodeup" from the reported value returned by MembersList.reason()

Currently, my choices (that I know of) are to hard-code/hand-code such a mapping in my code.

**Comment by phemmer** [comment]
That's a bug :-)

Fix was easy, but I'm adding a few tests. Should have fix pushed in a little bit.

**Comment by phemmer** [comment]
Fix pushed.
